# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Plugin-PseudoColumns
version:      0.02
version_from: lib/Class//DBI/Plugin/PseudoColumns.pm
installdirs:  site
requires:
    Class::DBI:                    0
    Data::Dumper:                  0
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
